name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
          - os: ubuntu-latest
            cc: clang
          - os: macos-latest
            cc: clang
          - os: windows-2022
            cc: cl

    steps:
      - uses: actions/checkout@v7

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - uses: actions/setup-python@v7
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install meson ninja

      - name: set up meson
        env:
          CC: ${{ matrix.cc }}
        run: meson setup build --buildtype=release --warnlevel=2

      - name: compile
        run: meson compile -C build

      - name: test
        run: meson test -C build -t 1200 --print-errorlogs

      - name: report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: meson test
          path: build/meson-logs/testlog.junit.xml
          reporter: java-junit
